import { categoriesData } from "../Categories/categoriesData.js";
import { imagesData } from "../Images/ImagesData.js";

export const productsData = [
  {
    id: 1,
    name: 'Свеча ароматическая "Кофе с молоком", в подарочной упаковке, 250мл',
    vendorCode: 586751,
    category: categoriesData[0].name,
    price: 900,
    oldPrice: 1590,
    images: imagesData[0].paths,
    mainImage: imagesData[0].paths[0],
  },
  {
    id: 2,
    name: 'Свеча ароматическая "Гранатовые брызги", в подарочной упаковке, 250мл',
    vendorCode: 586752,
    category: categoriesData[0].name,
    price: 900,
    oldPrice: 1590,
    images: imagesData[1].paths,
    mainImage: imagesData[1].paths[0],
  },
  {
    id: 3,
    name: 'Свеча ароматическая "Морская свежесть", в подарочной упаковке, 250мл',
    vendorCode: 586753,
    category: categoriesData[0].name,
    price: 900,
    oldPrice: 1590,
    images: imagesData[2].paths,
    mainImage: imagesData[2].paths[0],
  },
  {
    id: 4,
    name: 'Свеча ароматическая "Спелая груша", в подарочной упаковке, 250мл',
    vendorCode: 586754,
    category: categoriesData[0].name,
    price: 900,
    oldPrice: 1590,
    images: imagesData[3].paths,
    mainImage: imagesData[3].paths[0],
  },
  {
    id: 5,
    name: 'Свеча ароматическая "Восточные специи", в подарочной упаковке, 250мл',
    vendorCode: 586755,
    category: categoriesData[0].name,
    price: 900,
    oldPrice: 1590,
    images: imagesData[4].paths,
    mainImage: imagesData[4].paths[0],
  },
  {
    id: 6,
    name: 'Свеча ароматическая "Пачули и сандал", в подарочной упаковке, 250мл',
    vendorCode: 586756,
    category: categoriesData[0].name,
    price: 900,
    oldPrice: 1590,
    images: imagesData[5].paths,
    mainImage: imagesData[5].paths[0],
  },
  {
    id: 7,
    name: 'Свеча с посланием "Люблю тебя", аромат "Пряный апельсин", в подарочной упаковке, 250мл',
    vendorCode: 586757,
    category: categoriesData[0].name,
    price: 900,
    oldPrice: 1590,
    images: imagesData[6].paths,
    mainImage: imagesData[6].paths[0],
  },
  {
    id: 8,
    name: "Веник для бани дубовый, 2 штуки в комплекте",
    vendorCode: 586758,
    category: categoriesData[1].name,
    price: 900,
    oldPrice: 1590,
    images: imagesData[7].paths,
    mainImage: imagesData[7].paths[0],
  },
  {
    id: 9,
    name: "Брошь-булавка: Закат",
    vendorCode: 586759,
    category: categoriesData[2].name,
    price: 300,
    oldPrice: 710,
    images: imagesData[8].paths,
    mainImage: imagesData[8].paths[0],
  },
  {
    id: 10,
    name: "Брошь-булавка: Пингвин",
    vendorCode: 586760,
    category: categoriesData[2].name,
    price: 500,
    oldPrice: 910,
    images: imagesData[9].paths,
    mainImage: imagesData[9].paths[0],
  },
  {
    id: 11,
    name: "Брошь-булавка: Пицца",
    vendorCode: 586761,
    category: categoriesData[2].name,
    price: 800,
    oldPrice: 1210,
    images: imagesData[10].paths,
    mainImage: imagesData[10].paths[0],
  },
  {
    id: 12,
    name: "Брошь-булавка: Сердце",
    vendorCode: 586762,
    category: categoriesData[2].name,
    price: 700,
    oldPrice: 1110,
    images: imagesData[11].paths,
    mainImage: imagesData[11].paths[0],
  },
  {
    id: 13,
    name: "Брошь-булавка: Имбирный пряник",
    vendorCode: 586763,
    category: categoriesData[2].name,
    price: 700,
    oldPrice: 1110,
    images: imagesData[12].paths,
    mainImage: imagesData[12].paths[0],
  },
  {
    id: 14,
    name: "Брошь-булавка: Лягушонок",
    vendorCode: 586764,
    category: categoriesData[2].name,
    price: 800,
    oldPrice: 1210,
    images: imagesData[13].paths,
    mainImage: imagesData[13].paths[0],
  },
];
