export const productsDataExtra = [
  {
    id: 1,
    package: {
      unit: "мм",
      length: 100,
      width: 100,
      height: 100,
      weightUnit: "г",
      weight: 450,
    },
    brand: "Flammula",
    equipment: "Упаковка, инструкция, наклейка",
    color: "Белый",
    units: 1,
    aroma: "Кофе с молоком",
    burningTime: 40,
    diameter: {
      unit: "мм",
      quantity: 80,
    },
    volume: {
      unit: "мл",
      quantity: 250,
    },
    composition: {
      wax: "Кокосовый",
      wick: "Хлопковый",
    },
    candlestick: "Стекло",
    giftWrap: true,
    weight: { weightUnit: "г", weight: 400 },
    type: "Ручная работа",
  },
  {
    id: 2,
    package: {
      unit: "мм",
      length: 100,
      width: 100,
      height: 100,
      weightUnit: "г",
      weight: 450,
    },
    brand: "Flammula",
    equipment: "Упаковка, инструкция, наклейка",
    color: "Белый",
    units: 1,
    aroma: "Гранатовые брызги",
    burningTime: 40,
    diameter: {
      unit: "мм",
      quantity: 80,
    },
    volume: {
      unit: "мл",
      quantity: 250,
    },
    composition: {
      wax: "Кокосовый",
      wick: "Хлопковый",
    },
    candlestick: "Стекло",
    giftWrap: true,
    weight: { weightUnit: "г", weight: 400 },
    type: "Ручная работа",
  },
  {
    id: 3,
    package: {
      unit: "мм",
      length: 100,
      width: 100,
      height: 100,
      weightUnit: "г",
      weight: 450,
    },
    brand: "Flammula",
    equipment: "Упаковка, инструкция, наклейка",
    color: "Белый",
    units: 1,
    aroma: "Морская свежесть",
    burningTime: 40,
    diameter: {
      unit: "мм",
      quantity: 80,
    },
    volume: {
      unit: "мл",
      quantity: 250,
    },
    composition: {
      wax: "Кокосовый",
      wick: "Хлопковый",
    },
    candlestick: "Стекло",
    giftWrap: true,
    weight: { weightUnit: "г", weight: 400 },
    type: "Ручная работа",
  },
  {
    id: 4,
    package: {
      unit: "мм",
      length: 100,
      width: 100,
      height: 100,
      weightUnit: "г",
      weight: 450,
    },
    brand: "Flammula",
    equipment: "Упаковка, инструкция, наклейка",
    color: "Белый",
    units: 1,
    aroma: "Спелая груша",
    burningTime: 40,
    diameter: {
      unit: "мм",
      quantity: 80,
    },
    volume: {
      unit: "мл",
      quantity: 250,
    },
    composition: {
      wax: "Кокосовый",
      wick: "Хлопковый",
    },
    candlestick: "Стекло",
    giftWrap: true,
    weight: { weightUnit: "г", weight: 400 },
    type: "Ручная работа",
  },
  {
    id: 5,
    package: {
      unit: "мм",
      length: 100,
      width: 100,
      height: 100,
      weightUnit: "г",
      weight: 450,
    },
    brand: "Flammula",
    equipment: "Упаковка, инструкция, наклейка",
    color: "Белый",
    units: 1,
    aroma: "Восточные специи",
    burningTime: 40,
    diameter: {
      unit: "мм",
      quantity: 80,
    },
    volume: {
      unit: "мл",
      quantity: 250,
    },
    composition: {
      wax: "Кокосовый",
      wick: "Хлопковый",
    },
    candlestick: "Стекло",
    giftWrap: true,
    weight: { weightUnit: "г", weight: 400 },
    type: "Ручная работа",
  },
  {
    id: 6,
    package: {
      unit: "мм",
      length: 100,
      width: 100,
      height: 100,
      weightUnit: "г",
      weight: 450,
    },
    brand: "Flammula",
    equipment: "Упаковка, инструкция, наклейка",
    color: "Белый",
    units: 1,
    aroma: "Пачули и сандал",
    burningTime: 40,
    diameter: {
      unit: "мм",
      quantity: 80,
    },
    volume: {
      unit: "мл",
      quantity: 250,
    },
    composition: {
      wax: "Кокосовый",
      wick: "Хлопковый",
    },
    candlestick: "Стекло",
    giftWrap: true,
    weight: { weightUnit: "г", weight: 400 },
    type: "Ручная работа",
  },
  {
    id: 7,
    package: {
      unit: "мм",
      length: 100,
      width: 100,
      height: 100,
      weightUnit: "г",
      weight: 450,
    },
    brand: "Flammula",
    equipment: "Упаковка, инструкция, наклейка",
    color: "Белый",
    units: 1,
    aroma: "Пряный апельсин",
    burningTime: 40,
    diameter: {
      unit: "мм",
      quantity: 80,
    },
    volume: {
      unit: "мл",
      quantity: 250,
    },
    composition: {
      wax: "Кокосовый",
      wick: "Хлопковый",
    },
    candlestick: "Стекло",
    giftWrap: true,
    weight: { weightUnit: "г", weight: 400 },
    type: "Ручная работа",
  },
  {
    id: 8,
    package: {
      unit: "мм",
      length: 520,
      width: 310,
      height: 200,
      weightUnit: "г",
      weight: 600,
    },
    brand: "Flammula",
    color: "Зеленый",
    units: 2,
    broomType: "Дубовый",
    size: {
      sizeUnit: "см",
      length: 50,
      width: 30,
      height: 12,
    },
    weight: { weightUnit: "г", weight: 500 },
    type: "Ручная работа",
  },
  {
    id: 9,
    package: {
      unit: "мм",
      length: 55,
      width: 55,
      height: 20,
      weightUnit: "г",
      weight: 50,
    },
    brand: "Flammula",
    color: "Разноцветный",
    units: 1,
    size: {
      sizeUnit: "см",
      length: "5,5",
      width: "5,5",
    },
    materials: ["фетр", "мулине", "бисер"],
    weight: { weightUnit: "г", weight: 50 },
    type: "Ручная работа",
  },
  {
    id: 10,
    package: {
      unit: "мм",
      length: 60,
      width: 55,
      height: 20,
      weightUnit: "г",
      weight: 50,
    },
    brand: "Flammula",
    color: "Разноцветный",
    units: 1,
    size: {
      sizeUnit: "см",
      length: "6",
      width: "5,5",
    },
    materials: ["фетр", "мулине", "бисер"],
    weight: { weightUnit: "г", weight: 50 },
    type: "Ручная работа",
  },
  {
    id: 11,
    package: {
      unit: "мм",
      length: 55,
      width: 45,
      height: 20,
      weightUnit: "г",
      weight: 50,
    },
    brand: "Flammula",
    color: "Разноцветный",
    units: 1,
    size: {
      sizeUnit: "см",
      length: "5,5",
      width: "4,5",
    },
    materials: ["фетр", "мулине", "бисер"],
    weight: { weightUnit: "г", weight: 50 },
    type: "Ручная работа",
  },
  {
    id: 12,
    package: {
      unit: "мм",
      length: 60,
      width: 50,
      height: 20,
      weightUnit: "г",
      weight: 50,
    },
    brand: "Flammula",
    color: "Разноцветный",
    units: 1,
    size: {
      sizeUnit: "см",
      length: "6",
      width: "5",
    },
    materials: ["фетр", "мулине", "бисер"],
    weight: { weightUnit: "г", weight: 50 },
    type: "Ручная работа",
  },
  {
    id: 13,
    package: {
      unit: "мм",
      length: 70,
      width: 60,
      height: 20,
      weightUnit: "г",
      weight: 50,
    },
    brand: "Flammula",
    color: "Разноцветный",
    units: 1,
    size: {
      sizeUnit: "см",
      length: "7",
      width: "6",
    },
    materials: ["фетр", "мулине", "бисер"],
    weight: { weightUnit: "г", weight: 50 },
    type: "Ручная работа",
  },
  {
    id: 14,
    package: {
      unit: "мм",
      length: 70,
      width: 45,
      height: 20,
      weightUnit: "г",
      weight: 50,
    },
    brand: "Flammula",
    color: "Разноцветный",
    units: 1,
    size: {
      sizeUnit: "см",
      length: "7",
      width: "4,5",
    },
    materials: ["фетр", "мулине", "бисер"],
    weight: { weightUnit: "г", weight: 50 },
    type: "Ручная работа",
  },
];
